language: node_js
node_js: '8'
sudo: required
env:
  - COVERALLS_PARALLEL=true
services:
  - docker
script: ./ci/script.sh
after_script: ./ci/after-script.sh
jobs:
  include:
    - stage: build
      env: SERVICE=mavproxy
    - env: SERVICE=telemetry
    - env: SERVICE=interop-proxy
    - env: SERVICE=pong
    - env: SERVICE=forward-interop
    - env: SERVICE=imagery
    - env: SERVICE=dashboard
    - stage: test
      env: SERVICE_TEST=interop-proxy
    - env: SERVICE_TEST=pong
    - env: SERVICE_TEST=forward-interop
notifications:
  email: false
  webhooks:
    secure: YUGBaW1KnSX/z42uGA2a+DYIkAqVofJDmJdV3pdxR3oJpMyddbOsjSIVcndlFq6mKaoJfaQtBY46vsfEtiU9VbbMbToL6m+DMnFy0jgkfABIbH1mdX59hPEBjGIXF2KnYfO+JUGgAq36Te9wuzOYwBLgt2NYsUMunYFTXoCEj0rfJNwABxArIiuw3FXFOD3Oo+kWWq1QJrbF/0GCS/IcyonLpvDCUHiO+e7TbNQ3aY+8vQuPxf7U7aiVamRxIfKzhf9RFzTXv7vkLGKd6ojH+SQ+eduSIq9NJl9qDMxuCW0MVSxU2C00PdEcIGDEAdYmP3fIf8NZLdXYJlt2VEe1oGWKfkslBNwzw3xl4S5Dr4ka4QLaw3iu9JBl3kqigkVAzT9epy0HPlo7JT5odJnyMNsKr2mELtJM7aBVpzVVV2r7j3WDugB/0WZGhn0hRmB9DpFbEoXeWoc+9Wov50WZiLn7cf+Z+sOjnTO1XbAfWZ9iNOI3fEk96R1HZEMjnEz3hb7TD6u6Z3wTvJV4kRACdOzA/vFo14ELywiB7uQBHJba7mxHp4jOsqpuqRpb9jI7zQWPZaACjE+Bm/4b5xrGeX1Py+xVcGvkCYf1t81Pi5eNVjq05t8eXmw2MU4qkFo6C6bjB4/sQjYDWn9dFk19XL5KwNiWU2Hl31f7Fex5tTE=
  slack:
    secure: dk3vHsVYb08fJLQCwfjRpctNtV4SJWAjNExn+JQsl7I7KEh4UPoHe0W7hmyNEq3ckD69Us4yltPQPA9Yeh2xJTOGVmds/zZmuzz2t/fsbjTmV8KO4ncTPJPDNddhEdl/uYroKdrQbjqmTN7QLMTcjqoKT5UDi8SHZfGDx7QaNb/k8WnoxaRoRpFtYiLv6KC8PL5F/kGzcwC8akLbEZW676JuM7418QcJEpnvlJbDOObBr/7EoPJPUrm653ZQRAA2vSoL6BhORckDgS6m6DWjEtVlwi8q/c9EggdEGwy7Q0im2mnEuqRGnoYABG2GEoNDq0jMGBZnM34KpZTvX728j0WuWxOp4EdejTJSrIpsITEM875QR2LqjljlRpk/Ax0vziXWG4tpabb/lyOetujzveBPhrhWEuTTwJ/S5X4EsSbCjmUJuE2kI9tz5ETuSTJ9RvT9y8JrlCLtgs/epEAlC+PHnoHhOtCDJAvjAg8Pdq6tcPrA6ucvSELwt77wrW5pkjJ/iFOtg3aGXgFK2UBRDExaGW4GN4Vbm0b0zmlZVH2A/RoVZhvPx9/XQg7Nj2TaL40YjZYVPwMP4CMpgy8CAKrhEqqSDPznnNacm0D1XYsDDRCBValEt8NPaPm3r07UgzDFC6iK0CHUxMXe9r2maSRieSPjktdG1+weclVvPX8=
