language: generic
sudo: required
services:
  - docker
jobs:
  include:
    - stage: build
      env: SERVICE=mavproxy
      script: make "$SERVICE"
    - env: SERVICE=telemetry
      script: make "$SERVICE"
    - env: SERVICE=interop-proxy
      script: make "$SERVICE"
    - env: SERVICE=pong
      script: make "$SERVICE"
    - env: SERVICE=forward-interop
      script: make "$SERVICE"
    - env: SERVICE=imagery
      script: make "$SERVICE"
    - env: SERVICE=dashboard
      script: make "$SERVICE"
    - stage: test
      env: SERVICE=interop-proxy
      script: make "$SERVICE"-test
    - env: SERVICE=pong
      script: make "$SERVICE"-test
notifications:
  email: false
  slack:
    secure: dk3vHsVYb08fJLQCwfjRpctNtV4SJWAjNExn+JQsl7I7KEh4UPoHe0W7hmyNEq3ckD69Us4yltPQPA9Yeh2xJTOGVmds/zZmuzz2t/fsbjTmV8KO4ncTPJPDNddhEdl/uYroKdrQbjqmTN7QLMTcjqoKT5UDi8SHZfGDx7QaNb/k8WnoxaRoRpFtYiLv6KC8PL5F/kGzcwC8akLbEZW676JuM7418QcJEpnvlJbDOObBr/7EoPJPUrm653ZQRAA2vSoL6BhORckDgS6m6DWjEtVlwi8q/c9EggdEGwy7Q0im2mnEuqRGnoYABG2GEoNDq0jMGBZnM34KpZTvX728j0WuWxOp4EdejTJSrIpsITEM875QR2LqjljlRpk/Ax0vziXWG4tpabb/lyOetujzveBPhrhWEuTTwJ/S5X4EsSbCjmUJuE2kI9tz5ETuSTJ9RvT9y8JrlCLtgs/epEAlC+PHnoHhOtCDJAvjAg8Pdq6tcPrA6ucvSELwt77wrW5pkjJ/iFOtg3aGXgFK2UBRDExaGW4GN4Vbm0b0zmlZVH2A/RoVZhvPx9/XQg7Nj2TaL40YjZYVPwMP4CMpgy8CAKrhEqqSDPznnNacm0D1XYsDDRCBValEt8NPaPm3r07UgzDFC6iK0CHUxMXe9r2maSRieSPjktdG1+weclVvPX8=
